baseURL = "https://sonce.org/"
languageCode = "sl-si"
title = "Sindikat Sonce Koper"
canonifyURLs = true

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
news = "/news/:slug/"

[params]
  description = "Sindikat Sonce Koper – Brezplačna pravna pomoč in zaščita delavcev"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[mediaTypes]
  [mediaTypes."text/netlify"]
    suffixes = ["toml"]

[outputFormats]
  [outputFormats.Netlify]
    mediaType = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true