[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.121.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_VERSION = "0.121.0"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.121.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.121.0"

# Redirect rules for existing pages
[[redirects]]
  from = "/podpora.html"
  to = "/podpora/"
  status = 301

[[redirects]]
  from = "/pogoji-uporabe.html"
  to = "/pogoji-uporabe/"
  status = 301

[[redirects]]
  from = "/pravilnik-o-piskotkih.html"
  to = "/pravilnik-o-piskotkih/"
  status = 301

[[redirects]]
  from = "/pravilnik-o-zasebnosti.html"
  to = "/pravilnik-o-zasebnosti/"
  status = 301

# Enable Netlify Identity
[template.environment]
  HUGO_VERSION = "0.121.0"