backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "Novice"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Naslov", name: "title", widget: "string"}
      - {label: "Datum objave", name: "date", widget: "datetime"}
      - {label: "Povzetek", name: "summary", widget: "text", required: false}
      - {label: "Avtor", name: "author", widget: "string", default: "Sindikat Sonce Koper"}
      - {label: "Objavljeno", name: "draft", widget: "boolean", default: true}
      - {label: "Kategorije", name: "categories", widget: "list", default: ["novice"]}
      - {label: "Ključne besede", name: "tags", widget: "list", required: false}
      - {label: "Glavna slika", name: "featured_image", widget: "image", required: false}
      - {label: "Vsebina", name: "body", widget: "markdown"}