backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} \"{{slug}}\""
    update: "Update {{collection}} \"{{slug}}\""
    delete: "Delete {{collection}} \"{{slug}}\""
    uploadMedia: "Upload \"{{path}}\""
    deleteMedia: "Delete \"{{path}}\""

local_backend: true

media_folder: "static/uploads"
public_folder: "/uploads"

logo_url: "/images/soncelogo.jpg"

collections:
  - name: "news"
    label: "Novice"
    label_singular: "Novica"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    preview_path: "news/{{slug}}/"
    editor:
      preview: true
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Osnutek", name: "draft", widget: "boolean", default: true }
      - { label: "Izsek", name: "excerpt", widget: "text", required: false }
      - { label: "Hero slika", name: "hero", widget: "image", required: false, media_folder: "static/uploads/news", public_folder: "/uploads/news" }
      - { label: "Vsebina", name: "body", widget: "markdown" }