name: Import incoming news ZIPs

on:
  push:
    branches: [ main ]
    paths:
      - 'incoming/*.zip'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node dependencies
        run: npm ci | cat

      - name: Validate incoming ZIPs
        run: python tools/validate_incoming_zip.py | cat

      - name: Import incoming ZIPs
        run: python tools/import_incoming_zip.py | cat

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "ci: import incoming zips"
          else
            echo "No changes to commit in this step."
          fi
          # Always attempt to push in case the importer created commits
          git push || true

